export const APP_ACTIONS = {
  FETCH_BOOKS_DATA: 'FETCH_BOOKS_DATA',
  FETCH_BOOKS_DATA_RESOLVED: 'FETCH_BOOKS_DATA_RESOLVED',
  FETCH_BOOKS_DATA_RESOLVING: 'FETCH_BOOKS_DATA_RESOLVING',
  FETCH_BOOKS_DATA_ERROR: 'FETCH_BOOKS_DATA_ERROR',
  UPDATE_BOOK_DATA: 'UPDATE_BOOK_DATA',
  UPDATE_BOOK_DATA_RESOLVED: 'UPDATE_BOOK_DATA_RESOLVED',
  UPDATE_BOOK_DATA_RESOLVING: 'UPDATE_BOOK_DATA_RESOLVING',
  UPDATE_BOOK_DATA_ERROR: 'UPDATE_BOOK_DATA_ERROR',
  ADD_BOOK: 'ADD_BOOK',
  ADD_BOOK_RESOLVED: 'ADD_BOOK_RESOLVED',
  ADD_BOOK_RESOLVING: 'ADD_BOOK_RESOLVING',
  ADD_BOOK_ERROR: 'ADD_BOOK_ERROR',
  
};
